package ceui.lisa.whitefox

object Params {
    const val USER_JSON = "user_json"
    const val SONG_LIST_JSON = "{\n" +
            "    \"code\":200,\n" +
            "    \"relatedVideos\":null,\n" +
            "    \"playlist\":{\n" +
            "        \"id\":401594702,\n" +
            "        \"name\":\"『国语』\",\n" +
            "        \"coverImgId\":18638921115521636,\n" +
            "        \"coverImgUrl\":\"https://p1.music.126.net/avFX2mtDUunAxFBwhZgS0A==/18638921115521635.jpg\",\n" +
            "        \"coverImgId_str\":\"18638921115521635\",\n" +
            "        \"adType\":0,\n" +
            "        \"userId\":113568254,\n" +
            "        \"createTime\":1465949255268,\n" +
            "        \"status\":0,\n" +
            "        \"opRecommend\":false,\n" +
            "        \"highQuality\":false,\n" +
            "        \"newImported\":false,\n" +
            "        \"updateTime\":1600846841967,\n" +
            "        \"trackCount\":67,\n" +
            "        \"specialType\":0,\n" +
            "        \"privacy\":0,\n" +
            "        \"trackUpdateTime\":1615533314472,\n" +
            "        \"commentThreadId\":\"A_PL_0_401594702\",\n" +
            "        \"playCount\":275,\n" +
            "        \"trackNumberUpdateTime\":1600846841967,\n" +
            "        \"subscribedCount\":0,\n" +
            "        \"cloudTrackCount\":0,\n" +
            "        \"ordered\":true,\n" +
            "        \"description\":\"\",\n" +
            "        \"tags\":[\n" +
            "\n" +
            "        ],\n" +
            "        \"updateFrequency\":null,\n" +
            "        \"backgroundCoverId\":0,\n" +
            "        \"backgroundCoverUrl\":null,\n" +
            "        \"titleImage\":0,\n" +
            "        \"titleImageUrl\":null,\n" +
            "        \"englishTitle\":null,\n" +
            "        \"subscribers\":[\n" +
            "\n" +
            "        ],\n" +
            "        \"subscribed\":false,\n" +
            "        \"creator\":{\n" +
            "            \"defaultAvatar\":false,\n" +
            "            \"province\":1000000,\n" +
            "            \"authStatus\":0,\n" +
            "            \"followed\":false,\n" +
            "            \"avatarUrl\":\"http://p1.music.126.net/9BSnF5WgYnnBjIqi2aLm-w==/19085322835203895.jpg\",\n" +
            "            \"accountStatus\":0,\n" +
            "            \"gender\":2,\n" +
            "            \"city\":1005700,\n" +
            "            \"birthday\":877276800000,\n" +
            "            \"userId\":113568254,\n" +
            "            \"userType\":0,\n" +
            "            \"nickname\":\"CeuiLiSA\",\n" +
            "            \"signature\":\"ヒューマノイド\",\n" +
            "            \"description\":\"\",\n" +
            "            \"detailDescription\":\"\",\n" +
            "            \"avatarImgId\":19085322835203896,\n" +
            "            \"backgroundImgId\":109951163198268110,\n" +
            "            \"backgroundUrl\":\"http://p1.music.126.net/id-110tprTCxF4BXNbZIOw==/109951163198268119.jpg\",\n" +
            "            \"authority\":0,\n" +
            "            \"mutual\":false,\n" +
            "            \"expertTags\":null,\n" +
            "            \"experts\":null,\n" +
            "            \"djStatus\":0,\n" +
            "            \"vipType\":11,\n" +
            "            \"remarkName\":null,\n" +
            "            \"authenticationTypes\":0,\n" +
            "            \"avatarDetail\":null,\n" +
            "            \"avatarImgIdStr\":\"19085322835203895\",\n" +
            "            \"backgroundImgIdStr\":\"109951163198268119\",\n" +
            "            \"anchor\":false,\n" +
            "            \"avatarImgId_str\":\"19085322835203895\"\n" +
            "        },\n" +
            "        \"tracks\":[\n" +
            "            {\n" +
            "                \"name\":\"你不像她\",\n" +
            "                \"id\":368760,\n" +
            "                \"pst\":0,\n" +
            "                \"t\":0,\n" +
            "                \"ar\":[\n" +
            "                    {\n" +
            "                        \"id\":12438,\n" +
            "                        \"name\":\"南拳妈妈\",\n" +
            "                        \"tns\":[\n" +
            "\n" +
            "                        ],\n" +
            "                        \"alias\":[\n" +
            "\n" +
            "                        ]\n" +
            "                    }\n" +
            "                ],\n" +
            "                \"alia\":[\n" +
            "\n" +
            "                ],\n" +
            "                \"pop\":100,\n" +
            "                \"st\":0,\n" +
            "                \"rt\":\"600902000002550320\",\n" +
            "                \"fee\":8,\n" +
            "                \"v\":38,\n" +
            "                \"crbt\":null,\n" +
            "                \"cf\":\"\",\n" +
            "                \"al\":{\n" +
            "                    \"id\":36524,\n" +
            "                    \"name\":\"优の良曲 南搞小孩 (新歌+精选)\",\n" +
            "                    \"picUrl\":\"http://p4.music.126.net/rUMaj01wKrMeKnkgH3Z5ww==/109951163244870797.jpg\",\n" +
            "                    \"tns\":[\n" +
            "\n" +
            "                    ],\n" +
            "                    \"pic_str\":\"109951163244870797\",\n" +
            "                    \"pic\":109951163244870800\n" +
            "                },\n" +
            "                \"dt\":224000,\n" +
            "                \"h\":{\n" +
            "                    \"br\":320000,\n" +
            "                    \"fid\":0,\n" +
            "                    \"size\":8976761,\n" +
            "                    \"vd\":-5899\n" +
            "                },\n" +
            "                \"m\":{\n" +
            "                    \"br\":192000,\n" +
            "                    \"fid\":0,\n" +
            "                    \"size\":5386074,\n" +
            "                    \"vd\":-3300\n" +
            "                },\n" +
            "                \"l\":{\n" +
            "                    \"br\":128000,\n" +
            "                    \"fid\":0,\n" +
            "                    \"size\":3590730,\n" +
            "                    \"vd\":-1800\n" +
            "                },\n" +
            "                \"a\":null,\n" +
            "                \"cd\":\"1\",\n" +
            "                \"no\":2,\n" +
            "                \"rtUrl\":null,\n" +
            "                \"ftype\":0,\n" +
            "                \"rtUrls\":[\n" +
            "\n" +
            "                ],\n" +
            "                \"djId\":0,\n" +
            "                \"copyright\":1,\n" +
            "                \"s_id\":0,\n" +
            "                \"mark\":8192,\n" +
            "                \"originCoverType\":0,\n" +
            "                \"originSongSimpleData\":null,\n" +
            "                \"single\":0,\n" +
            "                \"noCopyrightRcmd\":null,\n" +
            "                \"rtype\":0,\n" +
            "                \"rurl\":null,\n" +
            "                \"mst\":9,\n" +
            "                \"cp\":1416500,\n" +
            "                \"mv\":0,\n" +
            "                \"publishTime\":1216915200000\n" +
            "            },\n" +
            "            {\n" +
            "                \"name\":\"可惜我是水瓶座\",\n" +
            "                \"id\":316654,\n" +
            "                \"pst\":0,\n" +
            "                \"t\":0,\n" +
            "                \"ar\":[\n" +
            "                    {\n" +
            "                        \"id\":10204,\n" +
            "                        \"name\":\"杨千嬅\",\n" +
            "                        \"tns\":[\n" +
            "\n" +
            "                        ],\n" +
            "                        \"alias\":[\n" +
            "\n" +
            "                        ]\n" +
            "                    }\n" +
            "                ],\n" +
            "                \"alia\":[\n" +
            "\n" +
            "                ],\n" +
            "                \"pop\":100,\n" +
            "                \"st\":0,\n" +
            "                \"rt\":\"\",\n" +
            "                \"fee\":8,\n" +
            "                \"v\":112,\n" +
            "                \"crbt\":null,\n" +
            "                \"cf\":\"\",\n" +
            "                \"al\":{\n" +
            "                    \"id\":31362,\n" +
            "                    \"name\":\"Simply Me\",\n" +
            "                    \"picUrl\":\"http://p3.music.126.net/8w4C39C2OY2fRANvkSXo9Q==/109951163270254519.jpg\",\n" +
            "                    \"tns\":[\n" +
            "\n" +
            "                    ],\n" +
            "                    \"pic_str\":\"109951163270254519\",\n" +
            "                    \"pic\":109951163270254510\n" +
            "                },\n" +
            "                \"dt\":216666,\n" +
            "                \"h\":{\n" +
            "                    \"br\":320000,\n" +
            "                    \"fid\":0,\n" +
            "                    \"size\":8669561,\n" +
            "                    \"vd\":-34800\n" +
            "                },\n" +
            "                \"m\":{\n" +
            "                    \"br\":192000,\n" +
            "                    \"fid\":0,\n" +
            "                    \"size\":5201754,\n" +
            "                    \"vd\":-32200\n" +
            "                },\n" +
            "                \"l\":{\n" +
            "                    \"br\":128000,\n" +
            "                    \"fid\":0,\n" +
            "                    \"size\":3467850,\n" +
            "                    \"vd\":-30300\n" +
            "                },\n" +
            "                \"a\":null,\n" +
            "                \"cd\":\"1\",\n" +
            "                \"no\":15,\n" +
            "                \"rtUrl\":null,\n" +
            "                \"ftype\":0,\n" +
            "                \"rtUrls\":[\n" +
            "\n" +
            "                ],\n" +
            "                \"djId\":0,\n" +
            "                \"copyright\":1,\n" +
            "                \"s_id\":0,\n" +
            "                \"mark\":8192,\n" +
            "                \"originCoverType\":1,\n" +
            "                \"originSongSimpleData\":null,\n" +
            "                \"single\":0,\n" +
            "                \"noCopyrightRcmd\":null,\n" +
            "                \"rtype\":0,\n" +
            "                \"rurl\":null,\n" +
            "                \"mst\":9,\n" +
            "                \"cp\":7003,\n" +
            "                \"mv\":0,\n" +
            "                \"publishTime\":1170259200000\n" +
            "            }]\n" +
            "}}"
}