package ceui.lisa.models

data class WebIllust(
    val alt: String? = null,
    val bookmarkData: Any? = null,
    val createDate: String? = null,
    val description: String? = null,
    val height: Int,
    val id: Long = 0L,
    val illustType: Int? = null,
    val isBookmarkable: Boolean? = null,
    val images: ImageUrls? = null,
    val isMasked: Boolean? = null,
    val isUnlisted: Boolean? = null,
    val pageCount: Int = 0,
    val aiType: Int = 0,
    val profileImageUrl: String? = null,
    val restrict: Int? = null,
    val sl: Int? = null,
    val title: String? = null,
    val updateDate: String? = null,
    val url: String? = null,
    val url_w: String? = null,
    val url_sm: String? = null,
    val url_s: String? = null,
    val urls: Map<String, String?>? = null,
    val userId: Long = 0L,
    val userName: String? = null,
    val width: Int,
    val xRestrict: Int? = null,
)